apply plugin: "java"
sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.resources.srcDirs = ["../android/assets"]
sourceCompatibility = 1.8


dependencies {
    implementation "com.badlogicgames.gdx:gdx-backend-headless:1.13.1"
    implementation "com.badlogicgames.gdx:gdx-platform:1.13.1:natives-desktop"

    implementation "com.github.crykn:kryonet:2.22.9"
    implementation project(":libGdxLib")
    implementation project(":Shared")
}